name: BUILD

on:
  push:
    branches: ['main', 'dev/**']
  pull_request:
    branches: ['main', 'dev/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: make DOCKER=1 .zig-docker
      - name: Check Format
        run: make DOCKER=1 format
      - name: Build Kernel (DEBUG)
        run: make DOCKER=1 debug
      - name: Build Kernel (RELEASE SAFE)
        run: make DOCKER=1 release
      - name: Build Kernel (RELEASE FAST)
        run: make DOCKER=1 fast