name: Build
on:
  push:
    branches: ['main', 'dev/**']
  pull_request:
    branches: ['main', 'dev/**']

env:
  NAME: kfs
  BOOTDIR: zig-cache
  BIN: zig-cache/kfs.elf
  ZIG_VERSION: 0.11.0
  ZIG_CACHE: zig-cache
  ZIG: /usr/zig/zig

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache zig installation
        id: cache-zig-installation
        uses: actions/cache@v3
        with:
          path: /usr/zig
          key: ${{ runner.os }}-zig
          restore-keys: |
            ${{ runner.os }}-zig

      - if: steps.cache-zig-installation.outputs.cache-hit != 'true'
        name: Install zig
        run: |
          wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-${ZIG_VERSION}.tar.xz -qO /tmp/zig.tar.xz
          sudo mkdir -p /usr/zig && echo "Zig folder created"
          sudo tar -xf /tmp/zig.tar.xz -C /usr/zig --strip-components=1 && echo "Zig extracted"

      - name: Build kernel sources
        run: make ${BIN}

